### PR TITLE
impr: OP-3247 Modernize the action

### PR DESCRIPTION
**Pull request by trend-adam-kinnell**
### Issue Link:

OP-3247, OP-3442

### What does it do?

+ Update all dependencies to the latest version. This removes deprecation warnings.
+ Add [skip actions] to the commit message to avoid infinite trigger loop (+ update test).
+ Update placeholder names and descriptions.
+ Rebuild the output code.
+ Add missing GitHub actions.

### Checklist

- [x] I will squash: PR title conforms to standard commit message format (`feat: XX-1234 ...`)
- [ ] I will merge without squashing: All commits conforms to standard commit message format (`feat: XX-1234 ...`)
- [ ] README update

### Testing

I added this action to `service-sample-repo` using this branch's version.
See https://github.com/cloudconformity/service-sample-repo/actions/runs/5352369651 for the run.

image

image

### CODE REVIEW

**Comment by trend-adam-kinnell** [comment]
Once this PR is merged I can update all repos to use this new version

**Review by dougallan-tm — DISMISSED** [review]
LGTM but don't take my work for it its Friday

**Comment by trend-adam-kinnell** [comment]
Even once this is merged, it won't be used by anything until we make more PRs so there isn't much in the way of risk

**Comment by johan1252** [comment]
image
🤯

**Comment by trend-adam-kinnell** [comment]
@johan1252 this repo wants us to commit the compiled action code to the repo so we get changes like in that screenshot

**Review by dougallan-tm — APPROVED** [review]
LGTM

**Review by NicholasValiente — APPROVED** [review]

**Pull request merged**
